export const GET_TRIVIA_QUESTIONS_REQUEST = "GET_TRIVIA_QUESTIONS_REQUEST";
export const GET_TRIVIA_QUESTIONS_SUCCESS = "GET_TRIVIA_QUESTIONS_SUCCESS";
export const GET_TRIVIA_QUESTIONS_FAILURE = "GET_TRIVIA_QUESTIONS_FAILURE";
